### ISSUE TITLE
Indentations differ across pages

### ISSUE THREAD

**Issue by bschilder** [christopherkenny/nature#3]
Hey there, 

Thanks so much for this awesome template! It's helped me push past a lot of latex issues i was running into previously.

One thing I was wondering, I noticed the amount of page indentation seems to alternate from page to page. 

Is this an intentional part of the format? Either way, is there a way to make the indentation consistent across all pages?
![Screenshot 2024-03-22 at 15 02 41](https://github.com/christopherkenny/nature/assets/34280215/421f7a5c-58ee-4dde-b71e-8f92ea8154e3)

Thanks, 
Brian

**Comment by christopherkenny** [comment]
Hi @bschilder. Sorry I missed this a while back. The template itself does not have even margins. Further, `geometry` is used in setting up the template (in the `.cls` file), so we can't do the normal thing with that. As such, I've added an `equal-margins` option to the template. 

Simply add:
```
equal-margins: true
```
